import type { ApprovalQueueItem, ReviewerProfile } from "@/types";
import { mockPlanSections } from "./mock-data";

export const mockReviewer: ReviewerProfile = {
  id: "reviewer-1",
  name: "Sarah Chen, CIM",
  email: "s.chen@finova.ai",
  role: "cim_reviewer",
};

const now = new Date();

function hoursFromNow(hours: number): string {
  return new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
}

function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

export const mockQueueItems: ApprovalQueueItem[] = [
  {
    id: "aq-001",
    planId: "plan-101",
    userAlias: "Northern_Investor",
    riskScore: 74,
    riskLabel: "Balanced",
    tier: "pro",
    province: "Ontario",
    age: 34,
    submittedAt: hoursAgo(2),
    slaDeadline: hoursFromNow(22),
    priority: "priority",
    plan: {
      id: "plan-101",
      userId: "user-101",
      status: "pending_review",
      healthScore: 74,
      riskLabel: "Balanced",
      createdAt: hoursAgo(2),
      sections: mockPlanSections,
      netWorth: "$342,500",
      monthlyCashFlow: "$1,850",
      savingsRate: "29.6%",
      retirementGap: "$28,000",
    },
  },
  {
    id: "aq-002",
    planId: "plan-102",
    userAlias: "PacificSaver_42",
    riskScore: 62,
    riskLabel: "Moderately Conservative",
    tier: "essential",
    province: "British Columbia",
    age: 42,
    submittedAt: hoursAgo(8),
    slaDeadline: hoursFromNow(16),
    priority: "standard",
    plan: {
      id: "plan-102",
      userId: "user-102",
      status: "pending_review",
      healthScore: 62,
      riskLabel: "Moderately Conservative",
      createdAt: hoursAgo(8),
      sections: mockPlanSections,
      netWorth: "$198,200",
      monthlyCashFlow: "$920",
      savingsRate: "14.2%",
      retirementGap: "$142,000",
    },
  },
  {
    id: "aq-003",
    planId: "plan-103",
    userAlias: "PrairiePlanner",
    riskScore: 85,
    riskLabel: "Growth",
    tier: "premium",
    province: "Alberta",
    age: 29,
    submittedAt: hoursAgo(6),
    slaDeadline: hoursFromNow(2),
    priority: "priority",
    plan: {
      id: "plan-103",
      userId: "user-103",
      status: "pending_review",
      healthScore: 85,
      riskLabel: "Growth",
      createdAt: hoursAgo(6),
      sections: mockPlanSections,
      netWorth: "$89,400",
      monthlyCashFlow: "$2,100",
      savingsRate: "34.8%",
      retirementGap: "$0",
    },
  },
  {
    id: "aq-004",
    planId: "plan-104",
    userAlias: "QC_Retraite",
    riskScore: 48,
    riskLabel: "Conservative",
    tier: "pro",
    province: "Quebec",
    age: 57,
    submittedAt: hoursAgo(26),
    slaDeadline: hoursAgo(2),
    priority: "standard",
    plan: {
      id: "plan-104",
      userId: "user-104",
      status: "pending_review",
      healthScore: 48,
      riskLabel: "Conservative",
      createdAt: hoursAgo(26),
      sections: mockPlanSections,
      netWorth: "$612,000",
      monthlyCashFlow: "$3,200",
      savingsRate: "22.1%",
      retirementGap: "$85,000",
    },
  },
  {
    id: "aq-005",
    planId: "plan-105",
    userAlias: "MaritimeMoney",
    riskScore: 71,
    riskLabel: "Balanced",
    tier: "essential",
    province: "Nova Scotia",
    age: 38,
    submittedAt: hoursAgo(4),
    slaDeadline: hoursFromNow(20),
    priority: "standard",
    plan: {
      id: "plan-105",
      userId: "user-105",
      status: "pending_review",
      healthScore: 71,
      riskLabel: "Balanced",
      createdAt: hoursAgo(4),
      sections: mockPlanSections,
      netWorth: "$245,800",
      monthlyCashFlow: "$1,440",
      savingsRate: "19.7%",
      retirementGap: "$62,000",
    },
  },
  {
    id: "aq-006",
    planId: "plan-106",
    userAlias: "CapitalGrowth99",
    riskScore: 91,
    riskLabel: "Aggressive",
    tier: "premium",
    province: "Ontario",
    age: 25,
    submittedAt: hoursAgo(1),
    slaDeadline: hoursFromNow(7),
    priority: "priority",
    plan: {
      id: "plan-106",
      userId: "user-106",
      status: "pending_review",
      healthScore: 91,
      riskLabel: "Aggressive",
      createdAt: hoursAgo(1),
      sections: mockPlanSections,
      netWorth: "$42,100",
      monthlyCashFlow: "$1,680",
      savingsRate: "38.2%",
      retirementGap: "$0",
    },
  },
];
