import { Nav } from "@/components/marketing/nav";
import { Footer } from "@/components/marketing/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Mosaic Finance",
  description:
    "Terms of service for Mosaic Finance. AI-generated financial plans reviewed by a registered professional.",
};

export default function TermsPage() {
  return (
    <main>
      <Nav hideAuth />

      <section className="bg-slate-950 px-6 pb-16 pt-32">
        <div className="mx-auto max-w-[760px]">
          <p className="mb-3 font-display text-xs font-semibold uppercase tracking-[0.1em] text-emerald">
            Terms of Service
          </p>
          <h1 className="font-display text-[32px] font-bold leading-tight text-text-inverse sm:text-[42px]">
            Clear terms, no surprises.
          </h1>
          <p className="mt-4 font-body text-base leading-relaxed text-text-inverse/60">
            Effective April 1, 2026 &middot; Last updated April 3, 2026
          </p>
        </div>
      </section>

      <section className="bg-warm-50 px-6 py-16">
        <div className="mx-auto max-w-[760px] space-y-12">
          <Block title="1. What Mosaic Finance Is">
            <p>
              Mosaic Finance (&ldquo;the Service&rdquo;) is an AI-powered
              financial planning tool operated by ChainForge Labs
              (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;), based
              in Saskatoon, Saskatchewan, Canada.
            </p>
            <p>
              The Service uses artificial intelligence to generate personalized
              financial plans based on information you provide. Every plan is
              reviewed by a registered financial professional before it is
              delivered to you.
            </p>
          </Block>

          <Block title="2. What Mosaic Finance Is Not">
            <div className="rounded-lg border border-warm-200 bg-white p-5">
              <p className="font-display text-sm font-semibold text-text-primary">
                Important Regulatory Disclaimer
              </p>
              <p className="mt-2">
                Mosaic Finance does not provide registered investment advice
                under Canadian securities legislation. The financial plans we
                generate are educational and informational in nature. They are
                not a substitute for advice from a registered investment
                advisor, financial planner, tax professional, or legal
                counsel.
              </p>
              <p className="mt-2">
                You should consult a qualified, registered professional before
                making any financial, investment, tax, or legal decisions based
                on content generated by Mosaic Finance.
              </p>
            </div>
          </Block>

          <Block title="3. Eligibility">
            <p>
              You must be at least 18 years of age and a resident of Canada to
              use Mosaic Finance. By creating an account, you confirm that you
              meet these requirements.
            </p>
          </Block>

          <Block title="4. Your Account">
            <ul>
              <li>
                You are responsible for maintaining the security of your
                account credentials
              </li>
              <li>
                You interact with Mosaic Finance using a self-chosen alias —
                we do not require your legal name
              </li>
              <li>
                You agree to provide accurate financial information to the
                extent you choose to share it; the quality of your plan depends
                on the accuracy of your inputs
              </li>
              <li>
                You may delete your account and all associated data at any
                time from your settings page
              </li>
            </ul>
          </Block>

          <Block title="5. Privacy &amp; Data">
            <p>
              We take your privacy seriously. We never collect your legal name,
              Social Insurance Number, bank credentials, or government ID.
              Your data is stored in Canada, encrypted, and never sold to third
              parties.
            </p>
            <p>
              For full details, see our{" "}
              <a
                href="/privacy"
                className="text-emerald underline underline-offset-2 hover:text-emerald-dark"
              >
                Privacy Policy
              </a>
              .
            </p>
          </Block>

          <Block title="6. AI-Generated Content">
            <ul>
              <li>
                Financial plans are generated by artificial intelligence
                (Anthropic&rsquo;s Claude) based on the information you provide
              </li>
              <li>
                AI-generated content may contain errors, inaccuracies, or
                recommendations that are not appropriate for your specific
                situation
              </li>
              <li>
                Every plan is reviewed by a registered financial professional
                before delivery, but this review does not constitute a
                client-advisor relationship
              </li>
              <li>
                You are solely responsible for any financial decisions you make
                based on the content of your plan
              </li>
            </ul>
          </Block>

          <Block title="7. Professional Review">
            <p>
              Plans generated through Mosaic Finance are reviewed by a
              registered financial professional before being delivered to you.
              This review is intended to verify the reasonableness and general
              accuracy of the AI-generated output. It does not create a
              fiduciary relationship, an advisor-client relationship, or any
              ongoing obligation between you and the reviewer.
            </p>
          </Block>

          <Block title="8. Subscriptions &amp; Payment">
            <ul>
              <li>
                Mosaic Finance offers free and paid subscription tiers, priced
                in Canadian dollars (CAD)
              </li>
              <li>
                Paid subscriptions are billed monthly through Stripe and
                auto-renew unless cancelled
              </li>
              <li>
                You may cancel your subscription at any time; access continues
                until the end of your current billing period
              </li>
              <li>
                We reserve the right to change pricing with 30 days&rsquo;
                notice to existing subscribers
              </li>
              <li>
                We do not collect or store your payment card information —
                all payment processing is handled by Stripe
              </li>
            </ul>
          </Block>

          <Block title="9. Acceptable Use">
            <p>You agree not to:</p>
            <ul>
              <li>
                Use the Service for any unlawful purpose or in violation of
                Canadian law
              </li>
              <li>
                Attempt to access another user&rsquo;s account or data
              </li>
              <li>
                Reverse-engineer, scrape, or extract data from the Service
                beyond your own account data
              </li>
              <li>
                Misrepresent Mosaic Finance output as registered investment
                advice when sharing with others
              </li>
              <li>
                Use the Service to generate plans for commercial resale
                without our written consent
              </li>
            </ul>
          </Block>

          <Block title="10. Intellectual Property">
            <p>
              The financial plans generated for you are yours to keep, download,
              and reference. The Mosaic Finance platform, brand, design, and
              underlying technology remain the property of ChainForge Labs.
            </p>
          </Block>

          <Block title="11. Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, ChainForge Labs
              and its officers, employees, and reviewers shall not be liable for
              any indirect, incidental, special, consequential, or punitive
              damages, or any loss of profits or revenues, whether incurred
              directly or indirectly, arising from:
            </p>
            <ul>
              <li>Your use of or reliance on AI-generated financial plans</li>
              <li>
                Any financial decisions you make based on content from the
                Service
              </li>
              <li>
                Errors, inaccuracies, or omissions in generated plans, even
                after professional review
              </li>
              <li>Service interruptions or data loss</li>
            </ul>
            <p>
              Our total liability for any claim arising from the Service is
              limited to the amount you have paid us in the 12 months preceding
              the claim.
            </p>
          </Block>

          <Block title="12. Termination">
            <p>
              You may terminate your account at any time by deleting it from
              your settings page. We may suspend or terminate your access if
              you violate these terms, with notice where reasonably
              practicable.
            </p>
          </Block>

          <Block title="13. Governing Law">
            <p>
              These terms are governed by the laws of the Province of
              Saskatchewan and the federal laws of Canada applicable therein.
              Any disputes arising from these terms or the Service will be
              resolved in the courts of Saskatchewan.
            </p>
          </Block>

          <Block title="14. Changes to These Terms">
            <p>
              We may update these terms from time to time. Material changes will
              be communicated via email to registered users at least 30 days
              before taking effect. Continued use of the Service after changes
              take effect constitutes acceptance.
            </p>
          </Block>

          <Block title="15. Contact">
            <p>
              Questions about these terms? Reach us at{" "}
              <a
                href="mailto:hello@mosaicfinance.ai"
                className="text-emerald underline underline-offset-2 hover:text-emerald-dark"
              >
                hello@mosaicfinance.ai
              </a>
              .
            </p>
            <p className="mt-2 text-text-muted">
              ChainForge Labs &middot; Saskatoon, Saskatchewan, Canada
            </p>
          </Block>
        </div>
      </section>

      <Footer />
    </main>
  );
}

function Block({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-3">
      <h2 className="font-display text-lg font-bold text-text-primary">
        {title}
      </h2>
      <div className="space-y-3 font-body text-[15px] leading-relaxed text-text-secondary [&_strong]:font-semibold [&_strong]:text-text-primary [&_ul]:list-none [&_ul]:space-y-2 [&_ul]:pl-0 [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:top-[10px] [&_li]:before:h-1.5 [&_li]:before:w-1.5 [&_li]:before:rounded-full [&_li]:before:bg-emerald">
        {children}
      </div>
    </div>
  );
}
