export function ComplianceFooter() {
  return (
    <footer className="py-6 px-6 text-center">
      <p className="font-[family-name:var(--font-body)] text-[11px] text-[var(--text-muted)] max-w-[800px] mx-auto leading-relaxed">
        Financial plans generated by Finova AI are reviewed by a CIM-designated professional.
        They do not constitute registered investment advice under Canadian securities legislation.
      </p>
    </footer>
  );
}
