import { MosaicLogo } from "./mosaic-logo";

export function Footer() {
  return (
    <footer className="border-t border-white/[0.06] bg-slate-950 px-6 py-10">
      <div className="mx-auto max-w-[1180px]">
        <div className="flex flex-col items-center gap-6 sm:flex-row sm:justify-between">
          <div className="flex items-center gap-3">
            <MosaicLogo size="sm" theme="dark" />
            <span className="font-body text-[13px] text-text-muted">
              &copy; 2026 ChainForge Labs
            </span>
          </div>

          <div className="flex gap-6">
            <a
              href="/privacy"
              className="font-body text-[13px] text-text-muted transition-colors hover:text-text-inverse"
            >
              Privacy Policy
            </a>
            <a
              href="/terms"
              className="font-body text-[13px] text-text-muted transition-colors hover:text-text-inverse"
            >
              Terms
            </a>
            <a
              href="mailto:hello@mosaicfinance.ai"
              className="font-body text-[13px] text-text-muted transition-colors hover:text-text-inverse"
            >
              Contact
            </a>
          </div>

          <p className="font-body text-[13px] text-text-muted">
            Canada
          </p>
        </div>

        <div className="mt-8 border-t border-white/[0.06] pt-6">
          <p className="mx-auto max-w-[900px] text-center font-body text-[11px] leading-relaxed text-text-muted">
            Financial plans generated by Mosaic Finance are reviewed by a
            registered financial professional. They do not constitute registered
            investment advice under Canadian securities legislation. Users should
            consult a registered advisor before acting on any information contained herein.
          </p>
        </div>
      </div>
    </footer>
  );
}
