import { Nav } from "@/components/marketing/nav";
import { Footer } from "@/components/marketing/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Mosaic Finance",
  description:
    "How Mosaic Finance protects your privacy. We never collect your legal name, SIN, bank credentials, or government ID.",
};

export default function PrivacyPage() {
  return (
    <main>
      <Nav hideAuth />

      <section className="bg-slate-950 px-6 pb-16 pt-32">
        <div className="mx-auto max-w-[760px]">
          <p className="mb-3 font-display text-xs font-semibold uppercase tracking-[0.1em] text-emerald">
            Privacy Policy
          </p>
          <h1 className="font-display text-[32px] font-bold leading-tight text-text-inverse sm:text-[42px]">
            Your data stays yours.
          </h1>
          <p className="mt-4 font-body text-base leading-relaxed text-text-inverse/60">
            Effective April 1, 2026 &middot; Last updated April 3, 2026
          </p>
        </div>
      </section>

      <section className="bg-warm-50 px-6 py-16">
        <div className="mx-auto max-w-[760px] space-y-12">
          <Block title="Our Core Commitment">
            <p>
              Mosaic Finance is built on a privacy-first principle: we collect
              only the minimum information required to generate a meaningful
              financial plan for you. We do not sell, rent, or share your
              personal data with third parties for marketing or advertising
              purposes — ever.
            </p>
          </Block>

          <Block title="What We Never Collect">
            <p>
              We have intentionally designed Mosaic Finance so that the
              following sensitive information is never requested, collected, or
              stored:
            </p>
            <ul>
              <li>Your legal name or government-issued identification</li>
              <li>Social Insurance Number (SIN)</li>
              <li>Bank account numbers, login credentials, or access tokens</li>
              <li>Credit card numbers (payments are processed securely by Stripe — we never see or store your card details)</li>
              <li>Exact home address</li>
              <li>Employer name or workplace details</li>
            </ul>
            <p>
              You interact with Mosaic Finance using a self-chosen alias. We
              do not require — or want — your real name.
            </p>
          </Block>

          <Block title="What We Do Collect">
            <p>
              To generate a personalized financial plan, we collect the
              following through our conversational onboarding:
            </p>
            <ul>
              <li>
                <strong>Profile information:</strong> your chosen alias,
                province of residence, age range, employment type, and family
                structure
              </li>
              <li>
                <strong>Financial information:</strong> income ranges, expense
                categories, savings goals, debt categories, investment holdings
                (account types and approximate values), and risk tolerance
              </li>
              <li>
                <strong>Conversation transcripts:</strong> your interactions
                with our AI planning assistant, used solely to build your plan
              </li>
              <li>
                <strong>Account credentials:</strong> email address and
                password (or Google OAuth) for authentication only
              </li>
            </ul>
          </Block>

          <Block title="How We Use Your Data">
            <p>Your data is used exclusively to:</p>
            <ul>
              <li>Generate your personalized financial plan using AI</li>
              <li>Enable a registered financial professional to review your plan before delivery</li>
              <li>Provide you with market context and insights relevant to your profile</li>
              <li>Send you notifications you have opted into (plan ready, weekly market updates)</li>
              <li>Improve the quality and accuracy of our planning tools</li>
            </ul>
            <p>
              We do not use your financial data to target advertising, build
              marketing profiles, or sell insights to third parties.
            </p>
          </Block>

          <Block title="Professional Review &amp; Confidentiality">
            <p>
              Every financial plan generated by Mosaic Finance is reviewed by a
              registered financial professional before delivery. Reviewers see
              your alias, province, age, risk profile, and plan content — never
              your email, legal identity, or raw financial account details.
              Reviewers are bound by professional confidentiality obligations.
            </p>
          </Block>

          <Block title="Data Storage &amp; Security">
            <ul>
              <li>
                All data is stored in Canada (Supabase hosted in{" "}
                <code>ca-central-1</code>, Montreal) and served from Canadian
                infrastructure (Vercel, Montreal region)
              </li>
              <li>Data is encrypted in transit (TLS) and at rest</li>
              <li>
                Database access is controlled through row-level security
                policies — you can only access your own data
              </li>
              <li>
                Payment processing is handled entirely by Stripe. We never
                receive, process, or store your payment card information
              </li>
            </ul>
          </Block>

          <Block title="Third-Party Services">
            <p>
              We use the following third-party services to operate Mosaic
              Finance. Each processes only the minimum data necessary for its
              function:
            </p>
            <ul>
              <li>
                <strong>Supabase</strong> — authentication and database hosting
                (Canada)
              </li>
              <li>
                <strong>Anthropic (Claude)</strong> — AI plan generation
                (conversational data is sent for processing; not used to train
                models)
              </li>
              <li>
                <strong>Stripe</strong> — payment processing (PCI-DSS
                compliant; we never handle card data)
              </li>
              <li>
                <strong>Resend</strong> — transactional email delivery
              </li>
              <li>
                <strong>Vercel</strong> — application hosting (Montreal region)
              </li>
              <li>
                <strong>Sentry</strong> — error monitoring (no personal
                financial data is sent; only technical error context)
              </li>
            </ul>
            <p>
              We do not use any advertising networks, tracking pixels, or
              data brokers.
            </p>
          </Block>

          <Block title="Your Rights">
            <p>You have the right to:</p>
            <ul>
              <li>
                <strong>Export your data</strong> — request a full copy of all
                data we hold about you
              </li>
              <li>
                <strong>Delete your data</strong> — permanently delete your
                account and all associated data at any time from your settings
                page
              </li>
              <li>
                <strong>Withdraw consent</strong> — stop using the service and
                request deletion at any time
              </li>
              <li>
                <strong>Opt out of communications</strong> — manage your
                notification preferences in settings or unsubscribe from any
                email
              </li>
            </ul>
          </Block>

          <Block title="Cookies &amp; Analytics">
            <p>
              Mosaic Finance uses only essential cookies required for
              authentication and session management. We do not use third-party
              advertising cookies or cross-site tracking.
            </p>
          </Block>

          <Block title="Children&rsquo;s Privacy">
            <p>
              Mosaic Finance is not intended for individuals under the age of
              18. We do not knowingly collect data from minors.
            </p>
          </Block>

          <Block title="Changes to This Policy">
            <p>
              We may update this policy from time to time. Material changes will
              be communicated via email to registered users. The effective date
              at the top of this page will always reflect the latest revision.
            </p>
          </Block>

          <Block title="Contact">
            <p>
              If you have questions about this privacy policy or your data,
              contact us at{" "}
              <a
                href="mailto:hello@mosaicfinance.ai"
                className="text-emerald underline underline-offset-2 hover:text-emerald-dark"
              >
                hello@mosaicfinance.ai
              </a>
              .
            </p>
            <p className="mt-2 text-text-muted">
              ChainForge Labs &middot; Saskatoon, Saskatchewan, Canada
            </p>
          </Block>
        </div>
      </section>

      <Footer />
    </main>
  );
}

function Block({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-3">
      <h2 className="font-display text-lg font-bold text-text-primary">
        {title}
      </h2>
      <div className="space-y-3 font-body text-[15px] leading-relaxed text-text-secondary [&_code]:rounded [&_code]:bg-warm-100 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-[13px] [&_strong]:font-semibold [&_strong]:text-text-primary [&_ul]:list-none [&_ul]:space-y-2 [&_ul]:pl-0 [&_li]:relative [&_li]:pl-5 [&_li]:before:absolute [&_li]:before:left-0 [&_li]:before:top-[10px] [&_li]:before:h-1.5 [&_li]:before:w-1.5 [&_li]:before:rounded-full [&_li]:before:bg-emerald">
        {children}
      </div>
    </div>
  );
}
